application:
  name: simple-example-node
  project: nocker
databases:
- type: postgresql
  version: "12"
  name: my-postgresql-969439
routers:
- name: main
  routes:
  - application_name: simple-example-node
    paths:
    - /
